server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=800MB
spring.servlet.multipart.max-request-size=850MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=CloudShare

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.username=:default
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
