server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/file_db
spring.datasource.username=postgres
spring.datasource.password=${Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=800MB
spring.servlet.multipart.max-request-size=850MB

cloudinary.cloud-name=${Cloudinary_Cloud_Name}
cloudinary.api-key=${Cloudinary_API_Key}
cloudinary.api-secret=${Cloudinary_API_Secret}

jwt.secret=${JWT_Secret}
jwt.expiration=86400000


management.endpoints.web.exposure.include=health,info,metrics
